import type { Metadata } from "next";
import { Roboto, Poppins, Luckiest_Guy } from "next/font/google";
import AuthProvider from "./clientLayout";
import { Toaster } from "sonner";
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["300", "400", "500", "700"],
});

const luckiest = Luckiest_Guy({
  weight: "400",
  subsets: ["latin"],
});

import "./globals.css";
import ClientProviders from "./clientprovider";

export const metadata: Metadata = {
  title: "BiteBlitz",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
          <ClientProviders>{children}</ClientProviders>
        </AuthProvider>
      </body>
    </html>
  );
}
